config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :meetings_apps
  resources :meetings
  root 'meetings_apps#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meeting.rb
# frozen_string_literal: true

class Meeting < ApplicationRecord
end

app/models/meetings_app.rb
# frozen_string_literal: true

class MeetingsApp < ApplicationRecord
  belongs_to :user

  validates :title, :description, :start_time, :end_time, :user_id, presence: true
  validates_datetime :start_time, on_or_after: -> { DateTime.current }
  validates :start_time, uniqueness: true
  validates_datetime :end_time, after: -> { DateTime.current }
  validates :end_time, uniqueness: true
  validates_datetime :end_time, after: :start_time
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, :encrypted_password, presence: true

  has_many :meetings_app
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/meetings_apps_controller.rb
# frozen_string_literal: true

class MeetingsAppsController < ApplicationController
  before_action :set_meetings_app, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]
  before_action :correct_user, only: %i[edit update destroy]

  # GET /meetings_apps or /meetings_apps.json
  def index
    @meetings_apps = MeetingsApp.all
  end

  # GET /meetings_apps/1 or /meetings_apps/1.json
  def show; end

  # GET /meetings_apps/new
  def new
    @meetings_app = current_user.meetings_app.build
  end

  # GET /meetings_apps/1/edit
  def edit; end

  # POST /meetings_apps or /meetings_apps.json
  def create
    @meetings_app = current_user.meetings_app.build(meetings_app_params)

    respond_to do |format|
      if @meetings_app.save
        format.html { redirect_to @meetings_app, notice: 'Meetings app was successfully created.' }
        format.json { render :show, status: :created, location: @meetings_app }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @meetings_app.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings_apps/1 or /meetings_apps/1.json
  def update
    respond_to do |format|
      if @meetings_app.update(meetings_app_params)
        format.html { redirect_to @meetings_app, notice: 'Meetings app was successfully updated.' }
        format.json { render :show, status: :ok, location: @meetings_app }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @meetings_app.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings_apps/1 or /meetings_apps/1.json
  def destroy
    @meetings_app.destroy
    respond_to do |format|
      format.html { redirect_to meetings_apps_url, notice: 'Meetings app was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def correct_user
    @meetings_app = current_user.meetings_app.find_by(id: params[:id])
    redirect_to meetings_apps_path, notice: 'Sem autorização para editar esta reunião' if @meetings_app.nil?
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_meetings_app
    @meetings_app = MeetingsApp.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def meetings_app_params
    params.require(:meetings_app).permit(:title, :description, :start_time, :end_time, :user_id)
  end
end

app/controllers/meetings_controller.rb
# frozen_string_literal: true

class MeetingsController < ApplicationController
  def index; end

  def show; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/meetings_apps_helper.rb
# frozen_string_literal: true

module MeetingsAppsHelper
end

app/helpers/meetings_helper.rb
# frozen_string_literal: true

module MeetingsHelper
end

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

  </head>
  <body>
    <% if notice %>
      <%= render 'layouts/alerts'%> 
    <% end %>
    <%= yield %>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>





<!DOCTYPE html>
<html>
  <head>    
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
</br> </br>
  <body>

  <%= render 'meetings/header' %>
    
  </body>
</html>

app/views/meetings/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
<%= link_to 'Sala de Reuniões', root_path, class:"navbar-brand" %>
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
        <li class="nav-item">
          <%= link_to "Criar Reuniões", new_meetings_app_path, class:"nav-link" %>
        </li>               

        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Editar Usuário ", edit_user_registration_path, class:"nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Sair", destroy_user_session_path, method: :delete, class:"nav-link" %>
          </li>

        <% else %> 
          <li class="nav-item">
            <%= link_to "Inscrever-se", new_user_registration_path, class:"nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Entrar", new_user_session_path, class:"nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/meetings/index.html.erb
<h1>Bem-vindo a Sala de Reuniões</h1>

app/views/meetings/show.html.erb
<h1>Meetings#show</h1>
<p>Find me in app/views/meetings/show.html.erb</p>

app/views/meetings_apps/_form.html.erb
<%= form_with(model: meetings_app) do |form| %>
  <% if meetings_app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meetings_app.errors.count, "error") %> prohibited this meetings_app from being saved:</h2>

      <ul>
        <% meetings_app.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :end_time %>
    <%= form.datetime_select :end_time, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :meetings_app_user_id, class:"form-control", value: current_user.id, type: :hidden %>
  </div>
  <br/>

  <div class="actions ">
    <%= form.submit %>
  </div>
<% end %>

<%= week_calendar(number_of_weeks: 2) do |date| %>
  <%= date %>
<% end %>

app/views/meetings_apps/edit.html.erb
<h1>Editing Meetings App</h1>

<%= render 'form', meetings_app: @meetings_app %>

<%= link_to 'Show', @meetings_app %> |
<%= link_to 'Back', meetings_apps_path %>

app/views/meetings_apps/index.html.erb
<p id="notice"><%= notice %></p>

<% if user_signed_in? %>
  <table class="table table-striped table-bordered table-hover">
    <thead class="table-dark">
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Start time</th>
        <th>End time</th>
        <th>User</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @meetings_apps.each do |meetings_app| %>
        <tr>
          <td><%= meetings_app.title %></td>
          <td><%= meetings_app.description %></td>
          <td><%= meetings_app.start_time %></td>
          <td><%= meetings_app.end_time %></td>
          <td><%= meetings_app.user_id %></td>
          <td><%= link_to 'Show', meetings_app %></td>
          <td><%= link_to 'Edit', edit_meetings_app_path(meetings_app) %></td>
          <td><%= link_to 'Destroy', meetings_app, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Meetings App', new_meetings_app_path, class:"btn btn-secondary" %>
<% else %>

  <h1>Bem-vindo a Sala de Reuniões</h1>
  
<% end %>

app/views/meetings_apps/new.html.erb
<h1>New Meetings App</h1>

<%= render 'form', meetings_app: @meetings_app %>

<%= link_to 'Back', meetings_apps_path %>

app/views/meetings_apps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @meetings_app.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @meetings_app.description %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @meetings_app.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @meetings_app.end_time %>
</p>

<p>
  <strong>User:</strong>
  <%= @meetings_app.user_id %>
</p>

<%= link_to 'Edit', edit_meetings_app_path(@meetings_app), class:"btn btn-secondary" %> 
<%= link_to 'Back', meetings_apps_path, class:"btn btn-secondary" %>